name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Lint project
      run: |
        if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then
          npx eslint . || true
        else
          echo "No ESLint config found, skipping lint"
        fi

    - name: Build project
      run: |
        if [ -f vite.config.js ] || [ -f vite.config.ts ]; then
          npm run build || true
        else
          echo "No Vite config found, skipping build"
        fi
